# Generated by Django 4.2.1 on 2023-05-31 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_person'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
